import matplotlib.pyplot as plt
import numpy as np

def plotGANGeneratorSamples(results):
    genSamples = results["generator_samples"]
    epochs = len(genSamples)
    imgsPerSample = genSamples[0].size(0)

    # Create a series of subplots
    fig, axs = plt.subplots(nrows=imgsPerSample,
                            ncols=epochs,
                            figsize=(epochs, imgsPerSample),
                            squeeze=False)
    
    for epoch, genSample in enumerate(genSamples):
        genSample = genSample.detach().cpu()

        # permute samples from BCHW -> BHWC (make matplotlib friendly)
        permutedSample = genSample.permute(0,2,3,1)
        for sampleIdx, img in enumerate(permutedSample):
            img = img.numpy()
            img = (img - img.min()) / (img.max() - img.min())

            ax = axs[sampleIdx, epoch]
            if img.shape[2] == 1:
                ax.imshow(img.squeeze(), cmap="gray")
            else:
                ax.imshow(img)
            ax.axis("off")

    bigAx = fig.add_subplot(111, frameon=False)
    bigAx.set_xticks(np.arange(epochs) + 0.5)
    bigAx.set_yticks(np.arange(imgsPerSample) + 0.5)

    bigAx.set_xticklabels([f"{i+1}" for i in range(epochs)])
    bigAx.set_yticklabels([f"{i}" for i in range(imgsPerSample)])

    bigAx.set_xlabel("Epoch")
    bigAx.set_ylabel("Latent Sample")

    bigAx.tick_params(labelcolor='black', top=False, bottom=False, left=False, right=False)

    fig.suptitle(f"Images Generated by GAN", fontsize=16)
    
    plt.tight_layout(rect=(0.0, 0.0, 1.0, 0.95))
    plt.show()